Encode TimeoutExpired texts
If there's a timeout, the error will have to be decoded because it's assumed to be encoded. This way we prevent crashes in the manager due to `AttributeError: 'str' object has no attribute 'decode'`